trigger:
  branches:
    include: ["main", "rel/*"]
  paths:
    exclude: ["*.md"]

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  DisableMAT: true

jobs:
  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
      - template: azure-pipelines/build.yml
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)/build_logs
          ArtifactName: build_logs
          ArtifactType: Container
        displayName: Publish build_logs artifacts
        condition: succeededOrFailed()
