trigger:
  branches:
    include: ["main", "rel/*"]
  paths:
    exclude: ["*.md"]

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  DisableMAT: true

jobs:
  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
      - template: azure-pipelines/build.yml
