// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.Web.LibraryManager.Vsix
{
    static class Vsix
    {
        public const string Id = "69b6bcde-f505-4c03-b071-8981cc1be2b9";
        public const string Name = "Microsoft Library Manager";
        public const string Description = @"Install client-side libraries easily to any web project";
        public const string Language = "en-US";
        public const string Author = "Microsoft";
        public const string Tags = "library, package, client-side, install";
    }
}
