// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.Web.LibraryManager.Vsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "75d8574c-9e92-482c-bf99-e7fba087c60e";
        public const string guidUiContextString = "f8c0db80-39c2-4f32-9be3-701f2d25add8";
        public const string guidUiContextConfigFileString = "f8c0db80-39c2-4f32-9be3-701f2d25add9";
        public const string guidLibraryManagerPackageCmdSetString = "44ee7bda-abda-486e-a5fe-4dd3f4cefac1";
        public const string guidVenusCmdIdString = "c7547851-4e3a-4e5b-9173-fa6e9c8bd82c";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidUiContext = new Guid(guidUiContextString);
        public static Guid guidUiContextConfigFile = new Guid(guidUiContextConfigFileString);
        public static Guid guidLibraryManagerPackageCmdSet = new Guid(guidLibraryManagerPackageCmdSetString);
        public static Guid guidVenusCmdId = new Guid(guidVenusCmdIdString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ConfigMenuGruop = 0x1030;
        public const int InstallPackage = 0x0100;
        public const int Clean = 0x0200;
        public const int Restore = 0x0300;
        public const int RestoreSolution = 0x0400;
        public const int RestoreOnBuild = 0x0500;
        public const int ManageLibraries = 0x0600;
        public const int IDG_VENUS_CTX_REFERENCE = 0x001B;
        public const int IDG_CTX_REFERENCE = 0x0102;
    }
}
