//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Web.LibraryManager.Vsix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Web.LibraryManager.Vsix.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client-Side Library.
        /// </summary>
        public static string AddClientSideLibrary {
            get {
                return ResourceManager.GetString("AddClientSideLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library {0} did not match the naming scheme for provider {1}. {2}.
        /// </summary>
        public static string BadLibraryId {
            get {
                return ResourceManager.GetString("BadLibraryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked {0} {1}.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose _specific files:.
        /// </summary>
        public static string ChooseSpecificFiles {
            get {
                return ResourceManager.GetString("ChooseSpecificFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean libraries started.
        /// </summary>
        public static string CleanLibrariesStarted {
            get {
                return ResourceManager.GetString("CleanLibrariesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean libraries succeeded.
        /// </summary>
        public static string CleanLibrariesSucceeded {
            get {
                return ResourceManager.GetString("CleanLibrariesSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabl&amp;e Client-Side Libraries on Build.
        /// </summary>
        public static string DisableRestoreOnBuild {
            get {
                return ResourceManager.GetString("DisableRestoreOnBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Enable Restore Client-Side Libraries on Build....
        /// </summary>
        public static string EnableRestoreOnBuild {
            get {
                return ResourceManager.GetString("EnableRestoreOnBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add libraries to project.
        /// </summary>
        public static string FailToAddLibrariesToProject {
            get {
                return ResourceManager.GetString("FailToAddLibrariesToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete libraries from project.
        /// </summary>
        public static string FailToDeleteLibrariesFromProject {
            get {
                return ResourceManager.GetString("FailToDeleteLibrariesFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include _all library files.
        /// </summary>
        public static string IncludeAllLibraryFiles {
            get {
                return ResourceManager.GetString("IncludeAllLibraryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeterminate {0} {1}.
        /// </summary>
        public static string Indeterminate {
            get {
                return ResourceManager.GetString("Indeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Library:.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was successfuly added to project.
        /// </summary>
        public static string LibraryAddedToProject {
            get {
                return ResourceManager.GetString("LibraryAddedToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was successfuly deleted from project.
        /// </summary>
        public static string LibraryDeletedFromProject {
            get {
                return ResourceManager.GetString("LibraryDeletedFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore completed. Files already up-to-date.
        /// </summary>
        public static string LibraryRestoredNoChange {
            get {
                return ResourceManager.GetString("LibraryRestoredNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files have been selected.
        /// </summary>
        public static string NoFilesSelected {
            get {
                return ResourceManager.GetString("NoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches found.
        /// </summary>
        public static string NoMatchesFound {
            get {
                return ResourceManager.GetString("NoMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing NuGet package containing MSBuild target....
        /// </summary>
        public static string Nuget_InstallingPackage {
            get {
                return ResourceManager.GetString("Nuget_InstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet package failed to install.
        /// </summary>
        public static string Nuget_PackageFailedToInstall {
            get {
                return ResourceManager.GetString("Nuget_PackageFailedToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet package failed to uninstall.
        /// </summary>
        public static string Nuget_PackageFailedToUninstall {
            get {
                return ResourceManager.GetString("Nuget_PackageFailedToUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet package installed.
        /// </summary>
        public static string Nuget_PackageInstalled {
            get {
                return ResourceManager.GetString("Nuget_PackageInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet package uninstalled.
        /// </summary>
        public static string Nuget_PackageUninstalled {
            get {
                return ResourceManager.GetString("Nuget_PackageUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling NuGet package....
        /// </summary>
        public static string Nuget_UninstallingPackage {
            get {
                return ResourceManager.GetString("Nuget_UninstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A NuGet package will be installed to augment the MSBuild process, but no files will be added to the project.
        ///
        ///This may require an internet connection.
        ///
        ///Do you want to continue?.
        /// </summary>
        public static string NugetInstallPrompt {
            get {
                return ResourceManager.GetString("NugetInstallPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Manager operation already in progress..
        /// </summary>
        public static string OperationInProgress {
            get {
                return ResourceManager.GetString("OperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Manager.
        /// </summary>
        public static string OutputWindowTitle {
            get {
                return ResourceManager.GetString("OutputWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages could not be loaded.
        /// </summary>
        public static string PackagesCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("PackagesCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Provider: .
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Choose a library to select files to install&gt;.
        /// </summary>
        public static string SelectLibraryToSelectFilesToInstall {
            get {
                return ResourceManager.GetString("SelectLibraryToSelectFilesToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates found at this time.
        /// </summary>
        public static string SuggestedAction_Update_NoUpdatesFound {
            get {
                return ResourceManager.GetString("SuggestedAction_Update_NoUpdatesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-release: {0}.
        /// </summary>
        public static string SuggestedAction_Update_Prerelease {
            get {
                return ResourceManager.GetString("SuggestedAction_Update_Prerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable: {0}.
        /// </summary>
        public static string SuggestedAction_Update_Stable {
            get {
                return ResourceManager.GetString("SuggestedAction_Update_Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Library.
        /// </summary>
        public static string SuggestedAction_Update_Title {
            get {
                return ResourceManager.GetString("SuggestedAction_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Target Location:.
        /// </summary>
        public static string TargetLocation {
            get {
                return ResourceManager.GetString("TargetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Type to search&gt;.
        /// </summary>
        public static string TypeToSearch {
            get {
                return ResourceManager.GetString("TypeToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnChecked {0} {1}.
        /// </summary>
        public static string UnChecked {
            get {
                return ResourceManager.GetString("UnChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall {0}.
        /// </summary>
        public static string UninstallLibrary {
            get {
                return ResourceManager.GetString("UninstallLibrary", resourceCulture);
            }
        }
    }
}
