//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Web.LibraryManager.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Web.LibraryManager.Resources.Text", typeof(Text).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean libraries operation was cancelled.
        /// </summary>
        public static string CleanLibrariesCancelled {
            get {
                return ResourceManager.GetString("CleanLibrariesCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} libraries failed to be deleted.
        /// </summary>
        public static string CleanLibrariesFailed {
            get {
                return ResourceManager.GetString("CleanLibrariesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean libraries started....
        /// </summary>
        public static string CleanLibrariesStarted {
            get {
                return ResourceManager.GetString("CleanLibrariesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} libraries were successfuly deleted .
        /// </summary>
        public static string CleanLibrariesSucceeded {
            get {
                return ResourceManager.GetString("CleanLibrariesSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean library {0} cancelled.
        /// </summary>
        public static string CleanLibraryCancelled {
            get {
                return ResourceManager.GetString("CleanLibraryCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean library {0} failed.
        /// </summary>
        public static string CleanLibraryFailed {
            get {
                return ResourceManager.GetString("CleanLibraryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean library {0} started....
        /// </summary>
        public static string CleanLibraryStarted {
            get {
                return ResourceManager.GetString("CleanLibraryStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean library {0} succeeded.
        /// </summary>
        public static string CleanLibrarySucceeded {
            get {
                return ResourceManager.GetString("CleanLibrarySucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean operation completed.
        /// </summary>
        public static string CleanOperationCompleted {
            get {
                return ResourceManager.GetString("CleanOperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download catalog from provider &quot;{0}&quot;.
        /// </summary>
        public static string FailedToDownloadCatalog {
            get {
                return ResourceManager.GetString("FailedToDownloadCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted.
        /// </summary>
        public static string FileDeleted {
            get {
                return ResourceManager.GetString("FileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete {0}.
        /// </summary>
        public static string FileDeleteFail {
            get {
                return ResourceManager.GetString("FileDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} written to destination.
        /// </summary>
        public static string FileWrittenToDisk {
            get {
                return ResourceManager.GetString("FileWrittenToDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install library {0} failed.
        /// </summary>
        public static string InstallLibraryFailed {
            get {
                return ResourceManager.GetString("InstallLibraryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install library {0} started....
        /// </summary>
        public static string InstallLibraryStarted {
            get {
                return ResourceManager.GetString("InstallLibraryStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library {0}  was successfuly restored.
        /// </summary>
        public static string InstallLibrarySucceeded {
            get {
                return ResourceManager.GetString("InstallLibrarySucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} libraries restored in {1} seconds.
        /// </summary>
        public static string LibrariesRestored {
            get {
                return ResourceManager.GetString("LibrariesRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update library information for {0}.
        /// </summary>
        public static string LibraryInfoUpdateFailed {
            get {
                return ResourceManager.GetString("LibraryInfoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore was cancelled for library {0}.
        /// </summary>
        public static string LibraryRestorationCancelled {
            get {
                return ResourceManager.GetString("LibraryRestorationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} libraries failed to restore.
        /// </summary>
        public static string LibraryRestorationFailed {
            get {
                return ResourceManager.GetString("LibraryRestorationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore completed. Files already up-to-date.
        /// </summary>
        public static string LibraryRestoredNoChange {
            get {
                return ResourceManager.GetString("LibraryRestoredNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries restore has been cancelled.
        /// </summary>
        public static string RestoreCancelled {
            get {
                return ResourceManager.GetString("RestoreCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more libraries failed to restore.
        /// </summary>
        public static string RestoreHasErrors {
            get {
                return ResourceManager.GetString("RestoreHasErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} libraries had restore cancelled.
        /// </summary>
        public static string RestoreLibrariesCancelled {
            get {
                return ResourceManager.GetString("RestoreLibrariesCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore libraries failed.
        /// </summary>
        public static string RestoreLibrariesFailed {
            get {
                return ResourceManager.GetString("RestoreLibrariesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore libraries started....
        /// </summary>
        public static string RestoreLibrariesStarted {
            get {
                return ResourceManager.GetString("RestoreLibrariesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} libraries restored successfuly.
        /// </summary>
        public static string RestoreLibrariesSucceeded {
            get {
                return ResourceManager.GetString("RestoreLibrariesSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled restore of library: {0}.
        /// </summary>
        public static string RestoreLibraryCancelled {
            get {
                return ResourceManager.GetString("RestoreLibraryCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restore library: {0}.
        /// </summary>
        public static string RestoreLibraryFailed {
            get {
                return ResourceManager.GetString("RestoreLibraryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore operation completed.
        /// </summary>
        public static string RestoreOperationCompleted {
            get {
                return ResourceManager.GetString("RestoreOperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring {0} -&gt; {1}..
        /// </summary>
        public static string RestoringLibrary {
            get {
                return ResourceManager.GetString("RestoringLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========== Finished ==========.
        /// </summary>
        public static string SummaryEndLine {
            get {
                return ResourceManager.GetString("SummaryEndLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Elapsed: {0}.
        /// </summary>
        public static string TimeElapsed {
            get {
                return ResourceManager.GetString("TimeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall {0}.
        /// </summary>
        public static string UninstallLibrary {
            get {
                return ResourceManager.GetString("UninstallLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update library {0} failed.
        /// </summary>
        public static string UpdateLibraryFailed {
            get {
                return ResourceManager.GetString("UpdateLibraryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update library {0} started... .
        /// </summary>
        public static string UpdateLibraryStarted {
            get {
                return ResourceManager.GetString("UpdateLibraryStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update library {0} succeeded.
        /// </summary>
        public static string UpdateLibrarySucceeded {
            get {
                return ResourceManager.GetString("UpdateLibrarySucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upadate operation completed.
        /// </summary>
        public static string UpdateOperationCompleted {
            get {
                return ResourceManager.GetString("UpdateOperationCompleted", resourceCulture);
            }
        }
    }
}
