//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Web.LibraryManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Web.LibraryManager.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: &lt;library&gt;@&lt;version&gt;.
        /// </summary>
        public static string CdnjsLibraryIdHintText {
            get {
                return ResourceManager.GetString("CdnjsLibraryIdHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} libraries had deletion cancelled.
        /// </summary>
        public static string Clean_NumberOfLibrariesCancelled {
            get {
                return ResourceManager.GetString("Clean_NumberOfLibrariesCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} libraries failed to be deleted.
        /// </summary>
        public static string Clean_NumberOfLibrariesFailed {
            get {
                return ResourceManager.GetString("Clean_NumberOfLibrariesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} libraries were successfully deleted in {1} secs.
        /// </summary>
        public static string Clean_NumberOfLibrariesSucceeded {
            get {
                return ResourceManager.GetString("Clean_NumberOfLibrariesSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean libraries operation was cancelled.
        /// </summary>
        public static string Clean_OperationCancelled {
            get {
                return ResourceManager.GetString("Clean_OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean libraries operation completed.
        /// </summary>
        public static string Clean_OperationCompleted {
            get {
                return ResourceManager.GetString("Clean_OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean operation completed with errors.
        /// </summary>
        public static string Clean_OperationCompletedWithErrors {
            get {
                return ResourceManager.GetString("Clean_OperationCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean operation failed for {0} libraries.
        /// </summary>
        public static string Clean_OperationFailed {
            get {
                return ResourceManager.GetString("Clean_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean libraries operation started.
        /// </summary>
        public static string Clean_OperationStarted {
            get {
                return ResourceManager.GetString("Clean_OperationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file {0}....
        /// </summary>
        public static string DownloadingFile {
            get {
                return ResourceManager.GetString("DownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download catalog from provider &quot;{0}&quot;.
        /// </summary>
        public static string FailedToDownloadCatalog {
            get {
                return ResourceManager.GetString("FailedToDownloadCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted.
        /// </summary>
        public static string FileDeleted {
            get {
                return ResourceManager.GetString("FileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete {0}.
        /// </summary>
        public static string FileDeleteFail {
            get {
                return ResourceManager.GetString("FileDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid filesystem path..
        /// </summary>
        public static string FileSystemLibraryIdHintText {
            get {
                return ResourceManager.GetString("FileSystemLibraryIdHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} written to destination.
        /// </summary>
        public static string FileWrittenToDisk {
            get {
                return ResourceManager.GetString("FileWrittenToDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install library {0} failed.
        /// </summary>
        public static string Install_LibraryFailed {
            get {
                return ResourceManager.GetString("Install_LibraryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install library {0} started.
        /// </summary>
        public static string Install_LibraryStarted {
            get {
                return ResourceManager.GetString("Install_LibraryStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: &lt;library&gt;@&lt;version&gt;.
        /// </summary>
        public static string JsDelivrProviderHintText {
            get {
                return ResourceManager.GetString("JsDelivrProviderHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string LibraryDetail_Unavailable {
            get {
                return ResourceManager.GetString("LibraryDetail_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update library information for {0}.
        /// </summary>
        public static string LibraryInfoUpdateFailed {
            get {
                return ResourceManager.GetString("LibraryInfoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring libraries for project {0}.
        /// </summary>
        public static string Restore_LibrariesForProject {
            get {
                return ResourceManager.GetString("Restore_LibrariesForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore completed. Files already up-to-date.
        /// </summary>
        public static string Restore_LibrariesUptodate {
            get {
                return ResourceManager.GetString("Restore_LibrariesUptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore was cancelled for library {0}.
        /// </summary>
        public static string Restore_LibraryRestoreCancelled {
            get {
                return ResourceManager.GetString("Restore_LibraryRestoreCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restore library: {0}.
        /// </summary>
        public static string Restore_LibraryRestoreFailed {
            get {
                return ResourceManager.GetString("Restore_LibraryRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library {0}  was successfuly restored restored.
        /// </summary>
        public static string Restore_LibraryRestoreSucceeded {
            get {
                return ResourceManager.GetString("Restore_LibraryRestoreSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} libraries had restore cancelled.
        /// </summary>
        public static string Restore_NumberOfLibrariesCancelled {
            get {
                return ResourceManager.GetString("Restore_NumberOfLibrariesCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} libraries failed to restore.
        /// </summary>
        public static string Restore_NumberOfLibrariesFailed {
            get {
                return ResourceManager.GetString("Restore_NumberOfLibrariesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} libraries restored in {1} seconds.
        /// </summary>
        public static string Restore_NumberOfLibrariesSucceeded {
            get {
                return ResourceManager.GetString("Restore_NumberOfLibrariesSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} libraries are up-to-date.
        /// </summary>
        public static string Restore_NumberOfLibrariesUptodate {
            get {
                return ResourceManager.GetString("Restore_NumberOfLibrariesUptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore operation has been cancelled.
        /// </summary>
        public static string Restore_OperationCancelled {
            get {
                return ResourceManager.GetString("Restore_OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore operation completed.
        /// </summary>
        public static string Restore_OperationCompleted {
            get {
                return ResourceManager.GetString("Restore_OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore operation completed with errors.
        /// </summary>
        public static string Restore_OperationCompletedWithErrors {
            get {
                return ResourceManager.GetString("Restore_OperationCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore operation failed for {0} libraries.
        /// </summary>
        public static string Restore_OperationFailed {
            get {
                return ResourceManager.GetString("Restore_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more libraries failed to restore.
        /// </summary>
        public static string Restore_OperationHasErrors {
            get {
                return ResourceManager.GetString("Restore_OperationHasErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore operation started.
        /// </summary>
        public static string Restore_OperationStarted {
            get {
                return ResourceManager.GetString("Restore_OperationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring library {0}....
        /// </summary>
        public static string Restore_RestoreOfLibraryStarted {
            get {
                return ResourceManager.GetString("Restore_RestoreOfLibraryStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========== Finished ==========.
        /// </summary>
        public static string SummaryEndLine {
            get {
                return ResourceManager.GetString("SummaryEndLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Elapsed: {0}.
        /// </summary>
        public static string TimeElapsed {
            get {
                return ResourceManager.GetString("TimeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall of library {0} has been cancelled.
        /// </summary>
        public static string Uninstall_LibraryCancelled {
            get {
                return ResourceManager.GetString("Uninstall_LibraryCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall of library {0} failed.
        /// </summary>
        public static string Uninstall_LibraryFailed {
            get {
                return ResourceManager.GetString("Uninstall_LibraryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall of library {0} started.
        /// </summary>
        public static string Uninstall_LibraryStarted {
            get {
                return ResourceManager.GetString("Uninstall_LibraryStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall of library {0} succeeded.
        /// </summary>
        public static string Uninstall_LibrarySucceeded {
            get {
                return ResourceManager.GetString("Uninstall_LibrarySucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall operation completed.
        /// </summary>
        public static string Uninstall_OperationCompleted {
            get {
                return ResourceManager.GetString("Uninstall_OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall operation completed with errors.
        /// </summary>
        public static string Uninstall_OperationCompletedWithErrors {
            get {
                return ResourceManager.GetString("Uninstall_OperationCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: &lt;library&gt;@&lt;version&gt;.
        /// </summary>
        public static string UnpkgProviderHintText {
            get {
                return ResourceManager.GetString("UnpkgProviderHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update of library {0} has been cancelled.
        /// </summary>
        public static string Update_LibraryCancelled {
            get {
                return ResourceManager.GetString("Update_LibraryCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update library {0} failed.
        /// </summary>
        public static string Update_LibraryFailed {
            get {
                return ResourceManager.GetString("Update_LibraryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update of library {0} started.
        /// </summary>
        public static string Update_LibraryStarted {
            get {
                return ResourceManager.GetString("Update_LibraryStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update of library {0} succeeded.
        /// </summary>
        public static string Update_LibrarySucceeded {
            get {
                return ResourceManager.GetString("Update_LibrarySucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade operation completed.
        /// </summary>
        public static string Upgrade_OperationCompleted {
            get {
                return ResourceManager.GetString("Upgrade_OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade operation completed with errors.
        /// </summary>
        public static string Upgrade_OperationCompletedWithErrors {
            get {
                return ResourceManager.GetString("Upgrade_OperationCompletedWithErrors", resourceCulture);
            }
        }
    }
}
